### ISSUE TITLE
Feature: Sort from lowest to highest?

### ISSUE THREAD

**Issue by danyim** [drbeco/nordping#3]
Hey there, thanks for sharing this useful script. I was wondering if it's possible to add a flag that'll return sorted results.

Currently I have to run `./nordping.sh > out` and parse `out` manually. Perhaps an extra feature would make it easier to display only the top `n` lowest ping server?

**Comment by drbeco** [comment]
The problem with sorting is that it requires a long time to ping all files.

Piping the whole script to sort is going to freeze the script.

I rather have the results appear as they are tested, so the user have that feedback.

**Comment by drbeco** [comment]
Implemented at commit fd78d882c33e9ad4a56a1f35e7d5059999a6aff8

See issue #9 

Thanks for your issue!
